#!/bin/bash

set -o errexit

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ZABBIX_VERSION="4.0"

echo "* get latest apt upgrades"
apt-get -y update
apt-get -qq upgrade

# skip zabbix-agent install on debian 10 cause of issues
if [[ $(lsb_release --release |awk '{print $2}') -lt 10 ]]; then
  echo "* Install zabbix-agent"
  export DEBIAN_FRONTEND=noninteractive
  wget https://download.qutic.com/src/zabbix/zabbix-release_${ZABBIX_VERSION}-3+stretch_all.deb
  dpkg -i zabbix-release_${ZABBIX_VERSION}-3+stretch_all.deb
  apt-get -y update
  apt-get -y install zabbix-agent || true
  mkdir -p /var/log/zabbix || true
  chown zabbix:zabbix /var/log/zabbix
  mkdir -p /etc/zabbix/zabbix_agentd.conf.d || true
fi

echo "* Add dtrace tools"
curl -sSLO https://download.qutic.com/src/joyent/dtracetools-lx_1.0_amd64.deb
dpkg -i dtracetools-lx_1.0_amd64.deb
rm dtracetools-lx_1.0_amd64.deb

echo "* Add bash extensions"
cat >> /etc/skel/.bashrc << EOF
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
alias la="ls -al"
alias t="cd /var/log/ && tail -n 50 -f "
alias msg="/usr/bin/tail -n 50 -f /var/log/syslog"
EDITOR=nano
HISTSIZE=2000
HISTFILESIZE=25000
HISTTIMEFORMAT="[%d.%m.%Y %T] "
export LANGUAGE=en_US.utf8
export LANG=en_US.utf8
EOF

echo "* Add nano extensions"
cat >> /etc/nanorc << EOF
include "/usr/share/nano/ruby.nanorc"
include "/usr/share/nano/sh.nanorc"
include "/usr/share/nano/nanorc.nanorc"
include "/usr/share/nano/html.nanorc"
include "/usr/share/nano/css.nanorc"
include "/usr/share/nano/javascript.nanorc"
EOF

echo "* Setup language env"
cp /etc/skel/.bashrc /root/.bashrc
source /root/.bashrc
locale-gen --purge en_US.UTF-8
# locale-gen en_US.utf8

echo "* Fix ntp error messages"
sed -i \
    -e "s/pool 0.debian.pool.ntp.org iburst/#pool 0.debian.pool.ntp.org iburst/" \
    -e "s/pool 1.debian.pool.ntp.org iburst/#pool 1.debian.pool.ntp.org iburst/" \
    -e "s/pool 2.debian.pool.ntp.org iburst/#pool 2.debian.pool.ntp.org iburst/" \
    -e "s/pool 3.debian.pool.ntp.org iburst/#pool 3.debian.pool.ntp.org iburst/" \
    /etc/ntp.conf

cat >> /etc/ntp.conf << EOF

# local clock = 127.127.1.0
server  127.127.1.0 prefer

EOF

echo "* setup bootstrap startscript"
touch /var/lib/bootstrap
systemctl daemon-reload
systemctl enable /etc/systemd/system/bootstrap.service

echo "* Cleaning up."
rm /var/lib/bootstrap 2>/dev/null || true
rm /root/.bash_history 2>/dev/null || true
history -c
