#!/bin/bash

set -o errexit

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ZABBIX_VERSION="4.0"

echo "* get latest apt upgrades"
apt-get -y update
apt-get -qq upgrade

echo "* Install zabbix-agent"
export DEBIAN_FRONTEND=noninteractive
wget "https://repo.zabbix.com/zabbix/${ZABBIX_VERSION}/ubuntu/pool/main/z/zabbix-release/zabbix-release_${ZABBIX_VERSION}-3+focal_all.deb"
/usr/bin/dpkg -i "zabbix-release_${ZABBIX_VERSION}-3+focal_all.deb"
apt-get -y update
apt-get -y install zabbix-agent || true
mkdir -p /var/log/zabbix || true
chown zabbix:zabbix /var/log/zabbix
mkdir -p /etc/zabbix/zabbix_agentd.conf.d || true
sed -i \
    "s|PIDFile=/run/zabbix/zabbix_agentd.pid|#PIDFile=/run/zabbix/zabbix_agentd.pid|" \
    /lib/systemd/system/zabbix-agent.service
sed -i \
    "s|PIDFile=/run/zabbix/zabbix_agentd.pid|#PIDFile=/run/zabbix/zabbix_agentd.pid|" \
    /etc/systemd/system/zabbix-agent.service

echo "* Add dtrace tools"
curl -sSLO https://download.qutic.com/src/joyent/dtracetools-lx_1.0_amd64.deb
/usr/bin/dpkg -i dtracetools-lx_1.0_amd64.deb
rm dtracetools-lx_1.0_amd64.deb

echo "* Add bash extensions"
cat >> /etc/skel/.bashrc << EOF
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
alias la="ls -Al"
alias t="cd /var/log/ && tail -n 50 -f "
alias msg="/usr/bin/tail -n 50 -f /var/log/syslog"
alias nano=vim
EDITOR=vim
HISTSIZE=2000
HISTFILESIZE=25000
HISTTIMEFORMAT="[%d.%m.%Y %T] "
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
EOF

echo "* Setup language env"
cp /etc/skel/.bashrc /root/.bashrc
source /root/.bashrc
# locale-gen en_US.utf8

echo "* Start rsyslog"
systemctl enable rsyslog
systemctl start rsyslog

echo "* setup bootstrap startscript"
touch /var/lib/bootstrap
systemctl daemon-reload
systemctl enable /etc/systemd/system/bootstrap.service

echo "* Cleaning up."
rm /var/lib/bootstrap 2>/dev/null || true
rm /root/.bash_history 2>/dev/null || true
history -c
